spring.application.name=ThreatWatch

#Redis Database Configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379

#Email Authentication Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_APP_USERNAME}
spring.mail.password=${MAIL_APP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#Email CVE Template Configuration
email.cve.description.product.length.lookup=99
email.cve.description.length.max=300