spring.application.name=ThreatWatch

#Redis Database Configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379

#NVD Configuration
backend.nvd.requests.interval=6000

#Email CVE Template Configuration
email.cve.description.product.length.lookup=140
email.cve.description.length.max=300